---
# tasks file for nginx
- name: Create destination
  file:
    path: /home/inception/nginx
    state: directory
    mode: "0755"
- name: Copy nginx assets
  ansible.builtin.copy:
    src: "assets"
    dest: "/home/inception/nginx"
- name: Copy nginx Dockerfile
  ansible.builtin.copy:
    src: "Dockerfile"
    dest: /home/inception/nginx


- name: building nginx image
  community.docker.docker_image:
    name: my_nginx
    build:
      path: /home/inception/nginx
    source: build
    tag: 1337

# - name: Tag nginx image for local registry
#   ansible.builtin.command:
#     cmd: docker tag my_nginx:latest localhost:5000/my_nginx:latest

# - name: Push nginx image to local registry
#   community.docker.docker_image:
#     name: localhost:5000/my_nginx
#     tag: latest
#     push: yes

# - name: Remove nginx image locally after push
#   community.docker.docker_image:
#     name: my_nginx
#     state: absent



# - name: Create destination
#   file:
#     path: /tmp/nginx
#     state: directory
#     mode: "0755"
# - name: Copy nginx assets
#   ansible.builtin.copy:
#     src: "assets"
#     dest: "/tmp/nginx"
# # - name: add execute permessions to scripts
# #   ansible.builtin.file:
# #     path: /tmp/nginx/assets/nginx_setup.sh
# #     mode: "0755"
# - name: Copy nginx Dockerfile
#   ansible.builtin.copy:
#     src: "Dockerfile"
#     dest: /tmp/nginx
# - name: building nginx image
#   community.docker.docker_image:
#     name: my_nginx
#     build:
#       path: /tmp/nginx
#     source: build