- name: SECONDPLAY
  hosts: all
  become: true
  vars_files:
    - secrets.yaml
  roles:
    - installdocker
    # - registry
    - mariadb
    - nginx
    - wordpress
    - compose
    # - deploy
  # tasks:
  #   - name: TRY ME
  #     ansible.builtin.ping:
