---
# tasks file for installdocker
# - name: Install Docker on Debian
#   hosts: all
#   become: true
#   tasks:

# - name: Installing Docker prerequisites
#   ansible.builtin.apt:
#     name:
#       - ca-certificates
#       - curl
#       - gnupg
#     update_cache: true

# - name: Create keyrings directory
#   ansible.builtin.file:
#     path: /etc/apt/keyrings
#     state: directory
#     mode: '0755'

# - name: Download Docker GPG key
#   ansible.builtin.get_url:
#     url: https://download.docker.com/linux/debian/gpg
#     dest: /etc/apt/keyrings/docker.asc
#     mode: "a+r"

# - name: Add Docker APT repository
#   ansible.builtin.apt_repository:
#     repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
#     filename: docker

# - name: Installing Docker
#   ansible.builtin.apt:
#     name:
#       - docker-ce
#       - docker-ce-cli
#       - containerd.io
#       - docker-buildx-plugin
#       - docker-compose-plugin
#     update_cache: true








- name: instlling docker prerequizet
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    update_cache: true
- name: create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
- name: Downloads Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "a+r"
- name: add docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
- name: instlling docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true