---
- name: Ensure database service directory exists
  ansible.builtin.file:
    path: "{{ app_root_dir }}/application"
    state: directory
    mode: "0755"

- name: Copy application configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ app_root_dir }}/application/"
  with_items:
    - set_up.sh
    - php.ini
    - Dockerfile

- name: Build application image
  community.docker.docker_image:
    name: "{{ org_prefix }}_application"
    build:
      path: "{{ app_root_dir }}/application"
    source: build
    tag: "{{ image_tag }}"